apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: litchi-backend # You'll need to manually type this out. The environment variable won't work
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: litchi-backend
    spec:     # pod spec                  
      containers: 
      - name: litchi-backend 
        image: gcr.io/litchi-backend/litchi-backend-devops:v1  # image we pushed
        ports:
        - containerPort: 8080

